[[cors]]
allowed_origins = "*"
allowed_methods = ["GET", "POST"]
allowed_headers = "*"

[[headers]]
for = ["**/*.woff2", "**/*.woff", "**/*.svg", "**/*.ttf", "**/*.otf", "**/*.eot", "**/*.js", "**/*.css"]
compress = "gzip"
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[headers]]
for = ["**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.gif", "**/*.webp"]
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[redirects]]
from = "/sites-internet-de-departements/introduction/index.html"
to = "/1-introduction/"

[[redirects]]
from = "/personnes/laura-fernandez/index.html"
to = "/laura-fernandez/"

[[redirects]]
from = "/equipe-editoriale/index.html"
to = "/personnes/equipe-editoriale/"

[[redirects]]
from = "/sites-internet-de-departements/2-la-solution-osuny/index.html"
to = "/2-la-solution-osuny/"

[[redirects]]
from = "/personnes/alain-pierre-forsans/index.html"
to = "/alain-pierre-forsans/"

[[redirects]]
from = "/iut-de-bordeaux/index.html"
to = "/organisations/iut-de-bordeaux/"

[[redirects]]
from = "/sites-internet-de-departements/1-introduction/index.html"
to = "/1-introduction/"

